### PR TITLE
Add `| xargs` 

### PR DESCRIPTION
**Pull request by cycool29**

### CODE REVIEW

**Comment by Botspot** [comment]
I'm not sure what error/problem this is trying to solve. Could you give an example where the current implementation without `xargs` would fail?

**Comment by cycool29** [comment]
Sorry for the late reply.

I have a XDM autostart file, and it messed up autostar: 

image

It shows `(yad:31596): Gtk-WARNING **: 14:45:21.097: Failed to set text from markup due to error parsing markup: Error on line 1 char 44: Element “markup” was closed, but the currently open element is “b”` error in the terminal output, which caused from `<b>$name</b>`.

I add an `echo "$LIST"` in the `main.sh`, and the `LIST` looks like this:
```
/home/pi/autostar/icons/txt.png
conky.desktop
<b>Conky</b>
Dec 03, 2021
bash -c 'conky -q -d -p 3 -y 20'
/home/pi/autostar/icons/txt.png
ulauncher.desktop
<b>Ulauncher</b>
Dec 06, 2021
env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window --hide-window
/home/pi/autostar/icons/txt.png
xdman.desktop
</b>treme Download Manager
Nov 30, 2021
"/opt/xdman/jre/bin/java" -Xmx1024m -jar "/opt/xdman/xdman.jar" -m
/home/pi/autostar/icons/txt.png
pi-apps-updater.desktop
<b>Pi Apps Updater</b>
Dec 06, 2021
/home/pi/testdir/pi-apps/updater onboot
/home/pi/autostar/icons/txt.png
Flameshot.desktop
<b>flameshot</b>
Nov 27, 2021
flameshot
```

Apparently, the problem is at `</b>treme Download Manager`.

When I delete the XDM autostart file, autostar works well:

image


Adding `xargs` doesn't work anymore, and I don't know why.

Here is the [XDM autostart file](https://transfer.sh/7Ho1tz/xdman.desktop).

**Comment by Botspot** [comment]
I figured it out. Your desktop file contained `\r` line-endings instead of `\n` line-endings.
Commit https://github.com/Botspot/autostar/commit/49212dfaef996bdc5302983c1b609f23ed260390 should fix this.
Let me know if you see any other regressions.

**Comment by cycool29** [comment]
Yes, it works now. Thanks!

**Pull request closed without merging**
